CREATE DATABASE MOBILES;

USE MOBILES;

SELECT * FROM MOBILES_WEB;

-- SHOW ONLY BRAND,PRICE,AND RATING
SELECT BRAND,PRICE,RATING
FROM MOBILES_WEB;

-- FIND TOTAL NUMBER OF MOBILES
SELECT COUNT(*) TOTAL_MOBILES
FROM MOBILES_WEB;

-- WHERE CLAUSE
-- GET MOBILES WITH PRICE > 20000
SELECT BRAND,PRICE FROM MOBILES_WEB
WHERE PRICE>20000;

-- GET MOBILES WITH RATING ABOVE 4.5
SELECT BRAND,RATING FROM MOBILES_WEB
WHERE RATING>4.5;

-- ORDER BY
-- SHOW TOP 10 MOST EXPENSIVE MOBILES
SELECT * FROM MOBILES_WEB
ORDER BY PRICE DESC
LIMIT 10;

-- SHOW LOWEST RATED MOBILES
SELECT BRAND,RATING,PRICE
FROM MOBILES_WEB
ORDER BY RATING ASC;

-- GROUP BY
-- FIND AVERAGE PRICE OF MOBILES FOR EACH BRAND
SELECT BRAND,AVG(PRICE) AVG_PRICE
FROM MOBILES_WEB
GROUP BY BRAND;

-- COUNT NUMBER OF MOBILES FOR EACH BRAND
SELECT BRAND,COUNT(*) TOTAL_MODELS
FROM MOBILES_WEB
GROUP BY BRAND;

-- FIND HIGHEST PRICED MOBILE FOR BRAND
SELECT BRAND, MAX(PRICE) MAX_PRICE
FROM MOBILES_WEB
GROUP BY BRAND;

-- FIND BRANDS WITH MORE THAN 5 MODELS
SELECT BRAND,COUNT(*) TOTAL_MODELS
FROM MOBILES_WEB
GROUP BY BRAND
HAVING COUNT(*) > 5;

-- FIND MODELS WITH DISCOUNT GREATER THAN 30%
SELECT * FROM MOBILES_WEB
WHERE DISCOUNT>30;

SELECT * FROM MOBILES_WEB;

-- GET TOP RATED MOBILE FOR EACH BRAND
SELECT BRAND,RATING,PRICE
FROM MOBILES_WEB M
WHERE RATING = (
	SELECT MAX(RATING)
    FROM MOBILES_WEB
    WHERE BRAND = M.BRAND);

-- FIND AVERAGE RATING AND TOTAL REVIEWS PER BRAND
SELECT BRAND, AVG(RATING) AVG_RATING,SUM(NUMBER_OF_REVIEWS) TOTAL_REVIEWS
FROM MOBILES_WEB
GROUP BY BRAND;

-- FIND BEST VALUE MOBILES(HIGH RATING + LOW PRICE)
SELECT * FROM MOBILES_WEB
ORDER BY RATING DESC, PRICE ASC;

-- FIND MOST POPULAR MOBILES( BASED ON RATING COUNT)
SELECT * FROM MOBILES_WEB
ORDER BY NUMBER_OF_RATINGS DESC
LIMIT 10;

-- FIND AVERAGE RATING BY RAM
SELECT RAM, AVG(RATING) AVG_RATING
FROM MOBILES_WEB
GROUP BY RAM
ORDER BY AVG_RATING DESC;

-- FIND MOBILES CONTAINING 5G
SELECT * FROM MOBILES_WEB
WHERE BRAND LIKE '%5G%';

-- COUNT MOBILES BY CAMERA TYPE
SELECT BRAND,CAMERA, COUNT(*) TOTAL_MOBILES
FROM MOBILES_WEB
GROUP BY CAMERA,BRAND
ORDER BY TOTAL_MOBILES DESC;


-- FOR VISUALIZATION
-- AVERAGE PRICE BY BRAND
SELECT BRAND,
       AVG(PRICE) AS AVG_PRICE
FROM MOBILES_WEB
GROUP BY BRAND;

-- HIGHEST DISCOUNT MOBILES
SELECT BRAND,PRICE,`ORIGINAL PRICE`, DISCOUNT
FROM MOBILES_WEB
ORDER BY DISCOUNT DESC
LIMIT 10;

-- TOP REVIWED MOBILES
SELECT BRAND,NUMBER_OF_REVIEWS
FROM MOBILES_WEB
ORDER BY NUMBER_OF_REVIEWS DESC
LIMIT 10;


-- Premium vs Budget Categorization
-- PREMIUM VS BUDGET MOBILES
SELECT BRAND,PRICE,
       CASE
           WHEN PRICE < 10000 THEN 'BUDGET'
           WHEN PRICE BETWEEN 10000 AND 30000 THEN 'MID-RANGE'
           ELSE 'PREMIUM'
       END AS PRICE_CATEGORY
FROM MOBILES_WEB;

-- BEST VALUE MOBILES
-- BEST VALUE MOBILES
SELECT BRAND,PRICE,RATING
FROM MOBILES_WEB
WHERE RATING >= 4.5
ORDER BY PRICE ASC;

-- Top 3 Expensive Mobiles Per Brand
-- TOP 3 EXPENSIVE MOBILES PER BRAND
SELECT *
FROM (SELECT BRAND,PRICE,
             ROW_NUMBER() OVER(
                 PARTITION BY BRAND
                 ORDER BY PRICE DESC) RN
FROM MOBILES_WEB) T
WHERE RN <= 3;

-- Customer Engagement by Brand
-- CUSTOMER ENGAGEMENT BY BRAND
SELECT BRAND,SUM(NUMBER_OF_RATINGS + NUMBER_OF_REVIEWS) TOTAL_ENGAGEMENT
FROM MOBILES_WEB
GROUP BY BRAND
ORDER BY TOTAL_ENGAGEMENT DESC;

-- Rating vs Price Analysis
-- RATING VS PRICE ANALYSIS
SELECT BRAND,PRICE,RATING
FROM MOBILES_WEB
ORDER BY RATING DESC, PRICE ASC;





